sudo: required
language: java
jdk:
- oraclejdk8
services:
  - docker
script:
- test/run.sh
after_success:
  - docker build -t ykhadilkar/rei-hello-world-spring-boot-docker .
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push ykhadilkar/rei-hello-world-spring-boot-docker;
    fi