sudo: required
language: java
jdk:
- oraclejdk8
services:
  - docker
script:
- test/run.sh
after_success:
  - docker build -t ykhadilkar/rei-hello-world-spring-boot-docker:latest .
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    clear;
    docker push ykhadilkar/rei-hello-world-spring-boot-docker:latest;
    fi